<a href="https://colab.research.google.com/github/Soham101003/pytorch_turtorial_yt/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


List


In [2]:
import numpy as np

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy array


In [4]:
np1=np.random.rand(3,4)
np1


array([[0.56063508, 0.7382833 , 0.57029906, 0.26573009],
       [0.02899016, 0.03777918, 0.94465243, 0.89969832],
       [0.32763169, 0.99735159, 0.13747394, 0.13135206]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.7977,  0.4062,  0.0690, -0.3157],
        [-1.6257, -0.5478,  0.1241,  0.6640],
        [ 0.0433,  0.2418,  0.7007,  0.4035]])

In [7]:
tensor_3d=torch.randn(2,3,4)
tensor_3d


tensor([[[-1.6791, -0.0762,  0.1775, -0.9814],
         [-0.5920, -0.8600,  1.0071,  0.8867],
         [ 0.5785,  1.4127,  0.3561, -0.1720]],

        [[-0.4706,  0.0952,  0.8611,  0.9248],
         [ 0.6288, -1.1266, -0.2018, -0.9772],
         [ 3.0623,  1.7296,  1.1626, -0.1171]]])

In [8]:
#create tensor out of numpy array
tensor_from_numpy=torch.tensor(np1)
tensor_from_numpy

tensor([[0.5606, 0.7383, 0.5703, 0.2657],
        [0.0290, 0.0378, 0.9447, 0.8997],
        [0.3276, 0.9974, 0.1375, 0.1314]], dtype=torch.float64)

In [9]:
torch.zeros([2, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(x[1][2])
x[0][1] = 8
print(x)

tensor(6)
tensor([[1, 8, 3],
        [4, 5, 6]])


In [13]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#reshape and view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
#reshape if the number of items is not known
my_torch2=torch.arange(20)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [22]:
my_torch2=my_torch2.reshape(5,-1)
my_torch2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [23]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch5[1]=400
my_torch5

tensor([  0, 400,   2,   3,   4,   5,   6,   7,   8,   9])

In [28]:
#slices
my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch7[7]=55
my_torch7[7]

tensor(55)

In [32]:
my_torch8=my_torch7.view(5,2)
my_torch8

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6, 55],
        [ 8,  9]])

In [33]:
my_torch8[:,1]

tensor([ 1,  3,  5, 55,  9])

In [34]:
my_torch8[:,1:]

tensor([[ 1],
        [ 3],
        [ 5],
        [55],
        [ 9]])

In [35]:
tensor_a=torch.tensor([1,2,3,4,5])
tensor_b=torch.tensor([6,7,8,9,10])

In [36]:
#addition of tensors
tensor_a+tensor_b

tensor([ 7,  9, 11, 13, 15])

In [38]:
#addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [39]:
#subtraction
tensor_a-tensor_b

tensor([-5, -5, -5, -5, -5])

In [41]:
#multiplication
tensor_a*tensor_b

tensor([ 6, 14, 24, 36, 50])

In [42]:
torch.mul(tensor_a,tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [43]:
#division
tensor_a/tensor_b

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [44]:
torch.div(tensor_a,tensor_b)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [47]:
#modulus
torch.remainder(tensor_a,tensor_b)


tensor([1, 2, 3, 4, 5])

In [49]:
#exponents
tensor_a**tensor_b

tensor([      1,     128,    6561,  262144, 9765625])

In [50]:
torch.pow(tensor_a,tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])